CREATE TYPE "PenetrationMode" AS ENUM (
  'PENETRATIONS_WITH_INSTALL',
  'PENETRATIONS_WITHOUT_INSTALL',
  'NO_PENETRATIONS'
);

ALTER TABLE "PoolModel"
ADD COLUMN "maxSkimmers" INTEGER,
ADD COLUMN "maxReturns" INTEGER,
ADD COLUMN "maxMainDrains" INTEGER;

ALTER TABLE "Order"
ADD COLUMN "penetrationMode" "PenetrationMode" NOT NULL DEFAULT 'PENETRATIONS_WITHOUT_INSTALL';
