ALTER TYPE "PenetrationMode" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "penetrationNotes" TEXT;

ALTER TABLE "PoolModel"
ADD COLUMN IF NOT EXISTS "hasIntegratedSpa" BOOLEAN NOT NULL DEFAULT false;
